name       : prison
version    : 5.82.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/prison-5.82.0.tar.xz : b86dc784e497c7e208f82234295041136d061d8b9372045f9d9ee8c6322ef6cf
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Cluase
    - MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
