name       : prison
version    : 5.42.0
release    : 2
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/prison-5.42.0.tar.xz : cfe77c2c2c27ee0e841334259a680bff3d1eeb60364069c2ac676bdea4130f2e
license    : MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
