name       : prison
version    : 5.43.0
release    : 3
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/prison-5.43.0.tar.xz : 0cabcb4bea129de67f0e1f9d4f7973c34067e6e6b56b95a11d9917fafa901305
license    : MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
