name       : prison
version    : 5.49.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/prison-5.49.0.tar.xz : 2d354ad8e262cfc6fa5f43c68a3231aa3dfc621f904a1f15a09aa0697afaf736
license    : MIT
component  : programming.library
optimize   : lto
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
builddeps  :
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
