name       : prison
version    : 5.46.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/prison-5.46.0.tar.xz : ef6a3f29e3f030e254343600f051317f6f8a99185d8ad93d78d849bf31bb0894
license    : MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
