name       : prison
version    : 5.61.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.61/prison-5.61.0.tar.xz : 9ebab1755e9d7cb01b2aa6e8b63640eb112d8557073423abdb94faecb42d87ab
license    : MIT
component  : programming.library
optimize   : lto
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
builddeps  :
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
