name       : prison
version    : 5.91.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/prison-5.91.0.tar.xz : 8f61c6c351e018df29a837a2d276d088b61fc844af406ea2d4f221f8e5b83f4c
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Cluase
    - MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
