name       : prison
version    : 5.83.0
release    : 45
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.83/prison-5.83.0.tar.xz : 6af9ecd86b07a055a16ba96dd01b69c5304f91307cdcc7c9b063fda5d561e2c8
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Cluase
    - MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
