name       : prison
version    : 5.99.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/prison-5.99.0.tar.xz : 84deb9c19e79ca73fee27151e140006f4eebd5326bc22a226a2b7bfbf074c1f1
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Cluase
    - MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
