name       : prison
version    : 5.76.0
release    : 37
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/prison-5.76.0.tar.xz : 6c369efc354f8f3a0e08b0de565fd523f1480d563bec0d19382e9ab01f3efb78
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Cluase
    - MIT
component  : programming.library
optimize   : lto
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
builddeps  :
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
