name       : prison
version    : 5.72.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/prison-5.72.0.tar.xz : 57263b30ebddf564200355bf202763d9314f52aa0c50621ed79a29c8ead4dccc
homepage   : https://community.kde.org/Frameworks
license    : MIT
component  : programming.library
optimize   : lto
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
builddeps  :
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
