name       : prison
version    : 5.41.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/prison-5.41.0.tar.xz : b1ef221964d479255ac1ded2a96b73f90723b8e69f3b3c9a86dd1f02860a7960
license    : MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
