name       : prison
version    : 5.107.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.107/prison-5.107.0.tar.xz : cc702edf7fd3f36b567ca2d1bfc315e80312e7e33fb6a0db49cc4a3b6fa64a9c
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Cluase
    - MIT
component  : programming.library
summary    : Qt api to produce QRCode barcode
description: |
    Prison is a barcode api currently offering a nice Qt api to produce QRCode barcodes and DataMatrix barcodes, and can easily be made support more.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(libdmtx)
    - pkgconfig(libqrencode)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
